import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val ktlint: String = "com.github.shyiko:ktlint:" + Versions.ktlint

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" + Versions.com_gradle_build_scan_gradle_plugin

    const val ktor_html_builder: String = "io.ktor:ktor-html-builder:" + Versions.io_ktor

    const val ktor_jackson: String = "io.ktor:ktor-jackson:" + Versions.io_ktor

    const val ktor_server_netty: String = "io.ktor:ktor-server-netty:" + Versions.io_ktor

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" + Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-js website](https://kotlinlang.org/) */
    const val kotlin_stdlib_js: String =
            "org.jetbrains.kotlin:kotlin-stdlib-js:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlinx-html-js website](https://github.com/Kotlin/kotlinx.html) */
    const val kotlinx_html_js: String =
            "org.jetbrains.kotlinx:kotlinx-html-js:" + Versions.kotlinx_html_js

    const val org_jlleitschuh_gradle_ktlint_idea_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint-idea:org.jlleitschuh.gradle.ktlint-idea.gradle.plugin:" + Versions.org_jlleitschuh_gradle_ktlint_idea_gradle_plugin

    /**
     * [slf4j-log4j12 website](http://www.slf4j.org) */
    const val slf4j_log4j12: String = "org.slf4j:slf4j-log4j12:" + Versions.slf4j_log4j12
}
